### ISSUE TITLE
How is update interval implemented

### ISSUE THREAD

**Issue by FlyingDiver** [elgatosf/streamdeck-analogclock#2]
This is probably a dumb question, because I don't do JavaScript much (mostly Python).

How is the update interval for the clock implemented.  I've been looking over all the code, and I can't figure out how the refresh is actually implemented.

**Comment by elgatosystems** [comment]
The AnalogClock simply uses the Javascript API `setInterval()` to refresh the clock every 1000ms. See here:

https://github.com/elgatosf/streamdeck-analogclock/blob/986ef891dbdeb22092999e7bdb57be337a300507/Sources/com.elgato.analogclock.sdPlugin/js/app.js#L135
