### ISSUE TITLE
Option to switch between digital/analog

### ISSUE THREAD

**Issue by panosru** [elgatosf/streamdeck-analogclock#3]
As the title says, it would be great if we had the option to display only the digital clock (with custom format)

**Comment by tiptronic** [comment]
@panosru What do you mean? If you don't want the time-string to get shown, just disable 'Show Title' from the little dropdown menu in the property inspector. This gives you just the analog clock...

**Comment by panosru** [comment]
@tiptronic I mean a toggle between only analogue and only digital. I know the plugin is called "Analog" clock, but it would be great if we could just use digital.

For example, I currently have the following setup which I accomplish by using the world clock (modified to remove the annoying globe background) or the left, and only analogue clock on the right.

It would be best to have this available in one plugin so I could just duplicate it and have it either analogue or digital.

![image](https://user-images.githubusercontent.com/400362/118482814-ed69ca80-b71d-11eb-9629-7241396950b9.png)


Thanks!

**Comment by tiptronic** [comment]
@panosru OK - understood... Good idea, although the AnalogClock is a sample to show how to draw from canvas to a key... but we'll see ;)

**Comment by panosru** [comment]
@tiptronic  I'm just throwing an idea :) feel free to close this _issue_ ;)

**Comment by tiptronic** [comment]
@panosru I added a digital option (see PI)... (no date, however ;))
